Update 2
ict283/ict283pass pull request #3
Opened 2021-02-11 05:01 UTC by JunoNgx

## Overview

Some minor tuning and readjustment I missed out. Hopefully the last one before I feel comfortable leaving it as it is.

## Changelog

* Add width constraint for the sessions/pricing section for less jarring visuals, as the cards are currently too wide. This only affects the desktop/large screen layout.
* Enlarge the collapsible links from `navbar` to make it more comfortable to select on a smartphone touchscreen.
* Remove the top padding from the banner/navbar area.
* Add margin to `big-heading` ("Data Structures and Abstractions") for better legibility.

As usual, let me know if I missed anything.

2021-02-11 11:15 UTC, ict283 requested changes
Small change here. Set <p> text to uniform grey colour. Rest looks good! Thanks
<img width="570" alt="Screenshot 2021-02-11 at 7 14 20 PM" src="https://user-images.githubusercontent.com/68686984/107629724-7dbaee00-6c9d-11eb-8b59-a2ed34fba730.png">

2021-02-11 11:15 UTC, ict283 commented on css/styles.css
> +  max-width: 1024px;
Width limit good

2021-02-11 11:15 UTC, ict283 commented on css/styles.css
> +    font-size: 1.5em;
Much needed change here

2021-02-13 13:29 UTC, JunoNgx commented
> 
> 
> Small change here. Set paragraph text to uniform grey colour. This quote is meant to be subtle. Rest looks good! Thanks
> <img alt="Screenshot 2021-02-11 at 7 14 20 PM" width="570" src="https://user-images.githubusercontent.com/68686984/107629724-7dbaee00-6c9d-11eb-8b59-a2ed34fba730.png">

Change pushed with improvement in the semantic use of html tags. Though the visual appearance has generally been reverted, the use of the tags were corrected.

2021-02-14 03:22 UTC, merged